# Generated by Django 5.0.7 on 2024-12-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frosted_Dreams', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
