# Generated by Django 5.0.7 on 2024-12-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frosted_Dreams', '0003_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
